config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create]
  resources :bookmarks, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true
  validates_uniqueness_of :movie, scope: :list
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
    @list = List.new
    @movie = Movie.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list_id)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.all
    @filtered_bookmarks = @bookmarks.select do |b|
      b.list_id == @list.id
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
<div class="container">
  <div style="display: flex; justify-content: space-between">
    <h1>My bookmarks</h1>
    <%= link_to 'Create a new bookmark', new_bookmark_path, class:"btn btn-gradient" %>
  </div>
  <% @bookmarks.each do |b| %>
    <div class="card-product">
        <img src="https://source.unsplash.com/random/?<%= b.movie.title %>" />
        <div class="card-product-infos">
          <h2><%= b.movie.title %> (<%= b.list.name %>)</h2>
          <p><%= b.comment %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
  <div style="display: flex; justify-content: space-between">
    <h1>Add new bookmark</h1>
    <%= link_to 'Back', bookmarks_path, class:"btn btn-gradient" %>
  </div>
  <%= simple_form_for(@bookmark) do |f| %>
  <%= f.association :movie, placeholder: 'select a movie' %>
  <%= f.association :list, placeholder: 'select a list' %>
  <%= f.input :comment, placeholder: 'type a comment' %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <div style="display: flex; align-items: center">
        <p style="padding-top: 12px"><strong>Powered by</strong></p>
        <a class="navbar-brand" href=<%= lists_path %> style="margin-left: 10px">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <%= link_to "My lists", lists_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My bookmarks", bookmarks_path, class: "nav-link" %>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        </div>
      </div>
    </div>
    <% if @list && @list.name != nil %>
      <% cloudinary = "https://res.cloudinary.com/jonathanjenin/image/upload/v1650740101/development/" %>
      <% @list.photo.key.nil? ? link = "https://source.unsplash.com/random/?" + @list.name.gsub(" ", "+") : link = cloudinary + @list.photo.key %>
    <% else %>
      <% link = "https://source.unsplash.com/random/?theatre" %>
    <% end %>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= link %>);">
      <div class="container">
        <h1>Save your next binge worthy movies!</h1>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='container'>
  <div style="display: flex; justify-content: space-between">
    <h1>My lists</h1>
    <%= link_to 'Create a new list', new_list_path, class:"btn btn-gradient" %>
  </div>
    <% @lists.each do |l| %>
      <% if l.photo.attached? %>
        <% link = "https://res.cloudinary.com/jonathanjenin/image/upload/v1650740101/development/" + l.photo.key %>
      <% else %>
        <% link = "https://source.unsplash.com/random/?" + l.name.gsub(" ", "+") %>
      <% end %>
      <div class="card-category"
      style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= link %>)">
        <%= link_to l.name, list_path(l) %>
      </div>
    <% end %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div style="display: flex; justify-content: space-between">
    <h1>Add new list</h1>
    <%= link_to 'Back', lists_path, class:"btn btn-gradient" %>
  </div>
  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name, placeholder: 'list name' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class='container'>
  <div style="display: flex; justify-content: space-between">
    <h1><%= @list.name %></h1>
    <div>
      <%= link_to 'Back', lists_path, class:"btn btn-gradient" %>
      <%= link_to 'Create a new bookmark', new_bookmark_path, class:"btn btn-gradient" %>
    </div>
  </div>

  <h6>There are <%= @filtered_bookmarks.count %> movie(s) attached to this list:</h6>
  <% @filtered_bookmarks.each do |f| %>
    <div class="card-product">
      <img src="https://source.unsplash.com/random/?<%= f.movie.title.gsub(" ", "+") %>" />
      <div class="card-product-infos">
        <h2><%= f.movie.title %> <%= link_to '🗑️',
                                  bookmark_path(f),
                                  method: :delete,
                                  data: {confirm: 'Are you sure?'} %></h2>
        <p><%= f.movie.overview %></p>
      </div>
    </div>
  <% end %>
</div>